config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  root to: 'items#index'
  get 'items/test' => 'items#test'
  resources :users do
    get 'sign_up_menu', on: :collection
    get 'phone_registration', on: :collection
    get 'complete_registration', on: :collection
    get 'information', on: :collection
    get 'logout', on: :collection
    get 'payment', on: :collection
    put 'information_update', on: :member
    put 'phone_confirmation', on: :member
    put 'phone_authenticated', on: :member
    get 'profile', on: :collection
    resources :addresses
    resources :payments
  end
  resources :items do
    resources :purchases, only: :index do
      post 'pay', on: :collection
      get 'done', on: :collection
    end
  end
  namespace :api do
    resources :items, only: :new, defaults: { format: 'json' }
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google, :facebook]

  has_many :items
  has_many :payments
  has_many :addresses
  has_many :notifications
  has_many :likes
  has_many :sns_credentials, dependent: :destroy

  validates :nickname, presence: true
  validates :nickname, uniqueness: true
  validates :family_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name, presence: true
  validates :first_name_kana, presence: true
  validates :birthday, presence: true

  protected
  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.create(first_name:     auth.info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         token:    auth.credentials.token,
                         password: Devise.friendly_token[0, 20],
                         meta:     auth.to_yaml)
    end
    user
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
 
    unless user
      user = User.new(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
      return {user: user}
    end
 
    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      render new_user_registration_url
    end
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    phone_registration_users_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    phone_registration_users_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ConfirmationSender
  include CodeGenerator

  before_action :set_category

  def sign_up_menu
    
  end

  def phone_registration
  end

  def phone_confirmation
    if current_user.update(phone: params[:user][:phone])
      ConfirmationSender.send_confirmation_to(current_user)
    else
      render :phone_registration
    end
  end

  def phone_authenticated
    if current_user.verification_code == params[:verification_code]
      current_user.update(authenticated: true)
    else
      render :phone_registration
    end
  end

  def complete_registration
  end

  def index
  end

  def show
  end

  def information
    @address = current_user.addresses.first()
  end

  def information_update
    
  end

  def logout
  end

  def payment
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = "sk_test_ea08d8eb3daefb829e554156"
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def profile
  end

  private
  def set_category
    @categories = Category.eager_load(children: :children).where(ancestry: nil)
  end
end

app/views/users/_mypage-left.html.haml
.left-content
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        %a.mypage-nav-list-item.active
          マイページ
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          お知らせ
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          やることリスト
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          いいね！一覧
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          出品する
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          出品した商品 - 出品中
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          出品した商品 - 取引中
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          出品した商品 - 売却済み
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          購入した商品 - 取引中
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          購入した商品 - 過去の取引
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          ニュース一覧
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          評価一覧
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          ガイド
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          お問い合わせ
          =fa_icon 'chevron-right',class:"icon-arrow"
    %h3.mypage-nav-head メルペイ
    %ul.mypage-nav-list
      %li
        %a.mypage-nav-list-item
          売上・振込申請
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          ポイント
          =fa_icon 'chevron-right',class:"icon-arrow"
    %h3.mypage-nav-head 設定
    %ul.mypage-nav-list
      %li
        %a.mypage-nav-list-item
          プロフィール
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          発送元・お届け先住所変更
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        = link_to '支払い方法', payment_users_path(), class:'mypage-nav-list-item'
      %li
        %a.mypage-nav-list-item
          メール/パスワード
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          本人情報
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        %a.mypage-nav-list-item
          電話番号の確認
          =fa_icon 'chevron-right',class:"icon-arrow"
      %li
        =link_to "ログアウト", logout_users_path,class: "mypage-nav-list-item"

app/views/users/complete_registration.html.haml
#users__complete_registration
  ユーザー登録が完了しました
  %br/
  %button
    =link_to 'トップページに戻る', root_path()

app/views/users/index.html.haml
.main-content
  .header.mypape_header
    = render 'items/header',layout: 'application'
  %nav.bread-crumbs
    %ul
      %li
        %a
          %span メルカリ
        =fa_icon 'chevron-right',class:"icon-arrow"
      %li.nowpage
        %span マイページ

  %main.mypage-container
    //left menu
    = render partial: 'mypage-left'

    .right-content
      %section.mypage-user-icon
        %a
          .mypage-icon
            %img{:alt => "", :height => "60", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "60"}/
          %h2.bold Kou
          .mypage-number
            %div.left
              評価
              %span.bold 6
            %div.right
              出品数
              %span.bold 4
      %section.mypage-tab-container-notification-todo
        %ul.mypage-tabs
          %li.tag1.active
            %h3
              %a
                お知らせ
          %li.tag2
            %h3
              %a
                やることリスト
        .tab-content
          %ul.mypage-item-list
            %li
              %a.mypage-item-link
                .mypage-icon
                  %img.lazyloaded{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                .mypage-item-body
                  .mypage-item-text 《大好評》必ずもらえる買う買うキャンペーン開催中！
                  .time
                    =fa_icon 'clock-o',class:"icon-clock"
                    %span 18 時間前
                =fa_icon 'chevron-right',class:"icon-arrow"
            %li
              %a.mypage-item-link
                .mypage-icon
                  %img.lazyloaded{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                .mypage-item-body
                  .mypage-item-text 明日、5%還元お得チケットの有効期限が切れます！タップして詳細を確認しましょう。
                  %time
                    =fa_icon 'clock-o',class:"icon-clock"
                    %span 20 時間前
                =fa_icon 'chevron-right',class:"icon-arrow"
            %li
              %a.mypage-item-link
                .mypage-icon
                  %img.lazyloaded{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                .mypage-item-body
                  .mypage-item-text 事務局から個別メッセージ「ログイン通知」
                  %time
                    =fa_icon 'clock-o',class:"icon-clock"
                    %span 2 日前
                =fa_icon 'chevron-right',class:"icon-arrow"
            %li
              %a.mypage-item-link
                .mypage-icon
                  %img.lazyloaded{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                .mypage-item-body
                  .mypage-item-text 事務局から個別メッセージ「ログイン通知」
                  %time
                    =fa_icon 'clock-o',class:"icon-clock"
                    %span 2 日前
                =fa_icon 'chevron-right',class:"icon-arrow"
            %li
              %a.mypage-item-link
                .mypage-icon
                  %img.lazyloaded{:alt => "", "data-src" => "//static.mercdn.net/images/mercari_profile.png", :src => "//static.mercdn.net/images/mercari_profile.png"}/
                .mypage-item-body
                  .mypage-item-text 事務局から個別メッセージ「ログイン通知」
                  %time
                    =fa_icon 'clock-o',class: "icon-clock"
                    %span 2 日前
                =fa_icon 'chevron-right',class:"icon-arrow"
            %li.mypage-go-list
              %a 一覧を見る
          -# %ul#mypage-tab-todo.mypage-item-list.tab-pane
            -# %li.mypage-item-not-found.bold 現在、やることリストはありません

      %section.mypage-tab-container
        %h2.mypage-tab-head 購入した商品
        %ul.mypage-tabs
          %li.active
            %h3
              %a
                取引中
          %li
            %h3
              %a
                過去の取引
        .tab-content
          %ul#mypage-tab-transaction-now.mypage-item-list.tab-pane.active
            %li.mypage-item-not-found.bold 取引中の商品がありません
          %ul#mypage-tab-transaction-old.mypage-item-list.tab-pane
            %li
              %a.mypage-item-link
                %figure
                  %img.lazyload
            %li
              %a.mypage-item-link
                %figure
                  %img.lazyload
            -# %li.mypage-go-list
            -#   %a 一覧を見る
  .footer
    = render "items/footer",layout: 'application'

app/views/users/information.html.haml
#users_information
  .main-content
    .header.mypape_header
      = render 'items/header',layout: 'application'
    %nav.bread-crumbs
      %ul
        %li
          %a
            %span メルカリ
          =fa_icon 'chevron-right',class:"icon-arrow"
        %li.nowpage
          %span マイページ

    %main.mypage-container
      //left menu
      = render partial: 'mypage-left'

      .right-content
        .heading
          本人情報の登録
        .main
          .nav
            お客さまの本人情報をご登録ください。
            %br/
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            =link_to '', class:"nav-link link-mercari-blue" do
              ='本人確認書類のアップロードについて'
              =fa_icon 'chevron-right',class:"icon-arrow"
          .edit-information
            =form_for current_user, url: information_update_user_path(current_user), method: :put do |f|
              .form-element
                %label お名前
                %br/
                ="#{current_user.family_name} #{current_user.first_name}"
              .form-element
                %label お名前カナ
                %br/
                ="#{current_user.family_name_kana} #{current_user.first_name_kana}"
              .form-element
                %label 生年月日
                %br/
                =current_user.birthday.strftime("%Y/%m/%d")
              .edit-information--postal_code.form-element
                = f.label :postal_code
                .input-any 任意
                %br/
                = f.text_field :postal_code, placeholder: "例)123-4567"
              .edit-information--prefecture.form-element
                = f.label :prefecture
                .input-any 任意
                %br/
                = f.select :prefecture, ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県",
                              "茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県",
                              "新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県",
                              "静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県",
                              "奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県",
                              "徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県",
                              "熊本県","大分県","宮崎県","鹿児島県","沖縄県"], {}
              .edit-information--city.form-element
                = f.label :city
                .input-any 任意
                %br/
                = f.text_field :city, placeholder: "例)横浜市緑区"
              .edit-information--house.form-element
                = f.label :house
                .input-any 任意
                %br/
                = f.text_field :house, placeholder: "例)青山1-1-1"
              .edit-information--building.form-element
                = f.label :building
                .input-any 任意
                %br/
                = f.text_field :building, placeholder: "例)柳ビル103"
              .edit-information--submit.form-element
                = f.submit

              =link_to '',class:"nav-link link-mercari-blue" do
                ='本人情報の確認について'
                =fa_icon 'chevron-right',class:"icon-arrow"

    .footer
      = render "items/footer",layout: 'application'

app/views/users/logout.html.haml
.mypage-nav-list-item#users_logout
  .main-content
    .header.mypape_header
      = render 'items/header',layout: 'application'
    %nav.bread-crumbs
      %ul
        %li
          %a
            %span メルカリ
          =fa_icon 'chevron-right',class:"icon-arrow"
        %li.nowpage
          %span マイページ

    %main.mypage-container
      //left menu
      = render partial: 'mypage-left'

      .right-content
        .main
          =link_to 'ログアウト', destroy_user_session_path(current_user), method: :delete , class:"btn-logout"

    .footer
      = render "items/footer",layout: 'application'

app/views/users/payment.html.haml
#users_payment
  .main-content
    .header.mypape_header
      = render 'items/header',layout: 'application'
    %nav.bread-crumbs
      %ul
        %li
          %a
            %span メルカリ
          =fa_icon 'chevron-right',class:"icon-arrow"
        %li.nowpage
          %span マイページ

    %main.mypage-container
      //left menu
      = render partial: 'mypage-left'

      .right-content
        .heading
          支払い方法
        .main
          .payments
            クレジットカード一覧
            .payment
              .payment__credit_card
                .payment__credit_card--icon
                  = image_tag "mc_vrt_pos.svg", width:"32px"
                .payment__credit_card--number
                  = "**** **** **** " + @default_card_information.last4
                .payment__credit_card--expiration_date
                  - exp_month = @default_card_information.exp_month.to_s
                  - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                  = exp_month + " / " + exp_year
                = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm", class:'payment__credit_card--btn') do
                  %input{ type: "hidden", name: "card_id", value: "", style: "clear:both;" }
                  %button 削除する
        .bottom
          =link_to '',class:"nav-link link-mercari-blue" do
            ='支払い方法について'
            =fa_icon 'chevron-right',class:"icon-arrow"

    .footer
      = render "items/footer",layout: 'application'

app/views/users/phone_authenticated.html.haml
#users__phone_authenticated
  電話番号の認証が完了しました！
  %button#go--address_registration
    =link_to 'お届け先住所の入力へ進む', new_user_address_path(current_user)

app/views/users/phone_confirmation.html.haml
#users__phone_confirmation
  = form_with url: phone_authenticated_user_path(current_user), local: true, method: :put  do |f|
    =f.text_field :verification_code
    SMS認証ボックス
    .actions
      =f.submit "SMS認証"

app/views/users/phone_registration.html.haml
#users__phone_registration
  =form_for current_user, url: phone_confirmation_user_path(current_user), local: true, method: :put do |f|
    %h2 電話番号の確認
    .field
      = f.label :phone
      %br/
      = f.text_field :phone, placeholder: "携帯電話の番号を入力"
      %br/
      %label
        本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
    .actions
      = f.submit "SMSを送信する"
      %br/
      %label
        ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
    -# .field
    -#   %button#btn_sms-confirmation
    -#     SMSを送信する
    -# #sms-confirmation
    -#   SMS認証ボックス
    -# .actions
    -#   = f.submit "SMS認証"
    =link_to '電話番号の確認が必要な理由', ''

app/views/users/profile.html.haml
.main-content.user_profile
  .header.mypape_header
    = render 'items/header',layout: 'application'
  %nav.bread-crumbs
    %ul
      %li
        %a
          %span メルカリ
        =fa_icon 'chevron-right',class:"icon-arrow"
      %li.nowpage
        %span マイページ


  %main.mypage-container.user_profile
    = render 'mypage-left'

    .right-content.user_profile-header
      %h2.user_profile-header-title プロフィール
      %section.user_profile-content
        %form
          %input.user_profile-input
          .user_profile-icon
            %figure.user_profile-icon_image
              %img{:height => "60", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "60"}/
            %input.input-default{:name => "nickname", :placeholder => "例)AYA☆セール中", :type => "text", :value => "Kou"}/
          .user_profile-content-main
            %textarea.textarea-default{:name => "introduction", :placeholder => "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
            %input{:name => "after_save_callback", :type => "hidden", :value => "https://www.mercari.com/jp/mypage/profile/"}/
            %button.btn-default.btn-red{:type => "submit"} 変更する



  .footer
    = render "items/footer",layout: 'application'

app/views/users/sign_up_menu.html.haml
#users__sign_up_menu
  .header
    =link_to '', class:'header--logo' do
      %img{:alt => "mercari", :height => "46", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3409339020"}/
  .main
    .main__nav
      新規会員登録
    .main__menu
      =link_to new_user_registration_path(),class:'main__menu__item main__menu--mail' do
        メールアドレスで登録
        .main__menu__item--icon
          =fa_icon 'envelope-o lg'
      =link_to user_facebook_omniauth_authorize_path(),class:'main__menu__item main__menu--facebook' do
        Facebookで登録
        .main__menu__item--icon
          =fa_icon 'facebook-square 2x'
      =link_to user_google_omniauth_authorize_path(), class:'main__menu__item main__menu--google' do
        Googleで登録
        .main__menu__item--icon
          %img{src:"https://img.icons8.com/color/30/000000/google-logo.png"}/
  .footer
    %ul.footer__links
      %li.footer__links__link
        =link_to 'プライバシーポリシー', ''
      %li.footer__links__link
        =link_to 'メルカリ利用規約', ''
      %li.footer__links__link
        =link_to '特定商取引に関する表記', ''
    .footer--logo
      =image_tag 'logo-gray.svg'
    .footer--copyright
      &copy; 2019 Mercari