config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  root to: 'items#index'
  get 'items/test' => 'items#test'
  resources :users do
    get 'sign_up_menu', on: :collection
    get 'phone_registration', on: :collection
    get 'complete_registration', on: :collection
    get 'information', on: :collection
    get 'logout', on: :collection
    get 'payment', on: :collection
    put 'information_update', on: :member
    put 'phone_confirmation', on: :member
    put 'phone_authenticated', on: :member
    get 'profile', on: :collection
    resources :addresses
    resources :payments
  end
  resources :items do
    resources :purchases, only: :index do
      post 'pay', on: :collection
      get 'done', on: :collection
    end
  end
  namespace :api do
    resources :items, only: :new, defaults: { format: 'json' }
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  # belongs_to :brand
  belongs_to :category
  validates :name,length: { in: 1..40 }
  validates :description,length: { in: 1..1000 }
  validates :price, numericality: true

  has_many_attached :images

  enum state:{
    "北海道":1,"青森県":2,"岩手県":3,"宮城県":4,"秋田県":5,"山形県":6,"福島県":7,
    "茨城県":8,"栃木県":9,"群馬県":10,"埼玉県":11,"千葉県":12,"東京都":13,"神奈川県":14,
    "新潟県":15,"富山県":16,"石川県":17,"福井県":18,"山梨県":19,"長野県":20,"岐阜県":21,
    "静岡県":22,"愛知県":23,"三重県":24,"滋賀県":25,"京都府":26,"大阪府":27,"兵庫県":28,
    "奈良県":29,"和歌山県":30,"鳥取県":31,"島根県":32,"岡山県":33,"広島県":34,"山口県":35,
    "徳島県":36,"香川県":37,"愛媛県":38,"高知県":39,"福岡県":40,"佐賀県":41,"長崎県":42,
              "熊本県":43,"大分県":44,"宮崎県":45,"鹿児島県":46,"沖縄県":47,"未定":99
  }
end

app/controllers/api/items_controller.rb
class Api::ItemsController < ApplicationController
  def new
    if(params[:select_item_0].present?)
      @midCategories = Category.where(ancestry: params[:select_item_0])
    end
    if(params[:select_item_0].present? && params[:select_item_1].present?)
      @smallCategories = Category.where(ancestry: "#{params[:select_item_0]}/#{params[:select_item_1]}")
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:index,:new, :show]

  def index
    @items = Item.all.limit(4)
    @mens = Item.where(Category_id: 95..120).limit(4).where(sold_out: 0)
    @ladies = Item.where(category_id:67...94).limit(4).where(sold_out: 0)
    @cosmes = Item.where(Category_id:140...162).limit(4).where(sold_out: 0)
    @kids = Item.where(Category_id: 121..139).limit(4).where(sold_out: 0)
    @chanels = Item.where(brand_id: 1).limit(4).where(sold_out: 0)
    @vuitton = Item.where(brand_id: 3).limit(4).where(sold_out: 0)
  end

    def test
    end

  def new
    @item =Item.new
    
  end

  def create
    @item=Item.new(item_params)


    if @item.save!
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @items = Item.new
    @userItems = @item.user.items
    @cateItems = Item.where("category_id = #{@item.category.id}").limit(3)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if(params[:item][:del_image_ids])
      params[:item][:del_image_ids].each do |del_image_id|
        image = @item.images.find(del_image_id)
        image.purge
      end
    end
    if @item.update!(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy!()
      redirect_to root_path
    else
      render :edit
    end

  end

  


  private

  def set_search
    @search = Item.ransack(params[:q])
  end

  def item_params
    params.require(:item).permit(:name ,:description ,:category_id ,:status ,:price, :state, :shipping_agency, :duration, images: []).merge(user_id: current_user.id)
  end

  def set_item
    @categories = Category.eager_load(children: :children).where(ancestry: nil)
  end
end

app/views/items/_footer.html.haml
//フッターアプリ広告
.footer-app_ad
  %div
    .footer-app_ad--text
      スマホでかんたんフリマアプリ
    .footer-app_ad--emotion
      今すぐ無料ダウンロード！
    .footer-app_ad_icons
      .footer-app_ad_icons--icon
        = image_tag 'mercari_icon.png', size:"70x70"
      .footer-app_ad_icons--icon
        = image_tag 'app-store.svg', class:'foreign_link'
      .footer-app_ad_icons--icon
        = image_tag 'google-play.svg', class:'foreign_link'
  .footer-app_ad--image
    = image_tag 'download_content_pc.png', height:"260"
//フッター最下ナビゲーション
.footer-nav-box
  .footer-nav-box__footer-navs
    %ul.footer-nav-box__footer-navs__about-mercari
      %li.footer-nav-box__footer-navs__about-mercari--caption
        ='メルカリについて'
      %li.footer-nav-box__footer-navs__about-mercari--item
        =link_to '会社概要（運営会社）'
      %li.footer-nav-box__footer-navs__about-mercari--item
        =link_to '採用情報'
      %li.footer-nav-box__footer-navs__about-mercari--item
        =link_to 'プレスリリース'
      %li.footer-nav-box__footer-navs__about-mercari--item
        =link_to '公式ブログ'
      %li.footer-nav-box__footer-navs__about-mercari--item
        =link_to 'メルカリロゴ利用ガイドライン'
      %li.footer-nav-box__footer-navs__about-mercari__links
        =link_to "", class:'footer-nav-box__footer-navs__about-mercari__links--twitter' do
          =fa_icon 'twitter 3x'
        =link_to "", class:'footer-nav-box__footer-navs__about-mercari__links--facebook' do
          =fa_icon 'facebook-square 3x'
    %ul.footer-nav-box__footer-navs__help-guide
      %li.footer-nav-box__footer-navs__help-guide--caption
        ='ヘルプ＆ガイド'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to 'メルカリガイド'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to 'らくらくメルカリ便'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to 'ゆうゆうメルカリ便'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to '大型メルカリ便'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to '車体取引ガイド'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to 'メルカリあんしん・あんぜん宣言！'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to '偽ブランド品撲滅への取り組み'
      %li.footer-nav-box__footer-navs__help-guide--item
        =link_to 'メルカリボックス'
    %ul.footer-nav-box__footer-navs__privacy-terms
      %li.footer-nav-box__footer-navs__privacy-terms--caption
        ='プライバシーと利用規約'
      %ul.footer-nav-box__footer-navs__privacy-terms__left
        %li.footer-nav-box__footer-navs__privacy-terms__left--item
          =link_to 'プライバシーポリシー'
        %li.footer-nav-box__footer-navs__privacy-terms__left--item
          =link_to 'メルカリ利用規約'
        %li.footer-nav-box__footer-navs__privacy-terms__left--item
          =link_to 'あんしんスマホサポート制度に関する利用特約'
        %li.footer-nav-box__footer-navs__privacy-terms__left--item
          =link_to 'コンプライアンスポリシー'
      %ul.footer-nav-box__footer-navs__privacy-terms__right
        %li.footer-nav-box__footer-navs__privacy-terms__right--item
          =link_to '個人データの安全管理に係る基本方針'
        %li.footer-nav-box__footer-navs__privacy-terms__right--item
          =link_to '特定商取引に関する表記'
        %li.footer-nav-box__footer-navs__privacy-terms__right--item
          =link_to '資金決済法に基づく表示'
        %li.footer-nav-box__footer-navs__privacy-terms__right--item
          =link_to '法令順守と犯罪抑止のために'
        %li.footer-nav-box__footer-navs__privacy-terms__right--item
          =link_to '返品・返金ポリシー'
    %ul.footer-nav-box__footer-navs__region
      %li.footer-nav-box__footer-navs__region--caption
        ='国'
      %li.footer-nav-box__footer-navs__region--item
        =link_to '日本'
      %li.footer-nav-box__footer-navs__region--item
        =link_to 'United States'
.footer-bottom
  .footer-logo
    = image_tag 'logo-white.svg'
  .footer-copyright
    &copy; 2019 Mercari

//出品ボタン
=link_to new_item_path do
  .footer-sell-btn
    .footer-sell-btn__decolations
    .footer-sell-btn__decolations--name
      出品
    =fa_icon 'camera 4x', class:"footer-sell-btn__decolations--icon"

app/views/items/_header.html.haml
%header.header
  .header-inner
    .header-top
      %h1
        %a{:href => "/"}
          %img{:alt => "mercari", :height => "36", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3409339020", :width => "134"}/
      %form.header-form{:action => "/"}
        %input.input-default{:name => "keyword", :placeholder => "何かお探しですか？", :type => "search", :value => ""}/
        =fa_icon 'search',class:"icon-search"
    .header-nav-box
      = render 'partial/header_l-left'


      .l-right
        -if user_signed_in?
          %ul.header-user-nav
            %li
              %a.header-menu-link
                =fa_icon 'bell',class:"icon-bell"
                %span お知らせ
            %li
              %a.header-menu-link
                =fa_icon 'check',class:"icon-check"
                %span やることリスト
            %li
              %a.header-user-icon.header-menu-link{:href => "users/profile"}
                .user
                  .user--img
                    %img{:alt => "", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "32"}/
                  .user--link
                    マイページ
        -else
          %ul.user-sign-nav
            %li
              =link_to 'ログイン', new_user_session_path(), class: 'user-sign-nav--login'
            %li
              =link_to '新規会員登録', '/users/sign_up_menu', class: 'user-sign-nav--regist'

app/views/items/_main-visual.html.haml
.swiper-container
  .swiper-wrapper
    .swiper-slide
      %img{:alt => "Swiper01", :src => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQthSbY-xTcz1tFXirn4YQRx8zCmaMZ0AJyvbHrcJKH2ORUl_V1og"}/
    .swiper-slide
      %img{:alt => "Swiper02", :src => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWrzF_4bEfOPwQmID6kNo97witB1dfigZ9sC4ZiPKt37CGSjVH"}/
    .swiper-slide
      %img{:alt => "Swiper03", :src => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZTp31H6CWxf73H8w05fTwtzHUpvh23fYgJv_E9F9ZdDs2XFs4"}/
  .swiper-pagination
  .swiper-button-prev
  .swiper-button-next
:javascript
  var swiper = new Swiper('.swiper-container', {
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
    loop: true,
    autoplay: {
      delay: 5000,
      autoHeight: true,
      disableOnInteraction: true
    },
    pagination: {
        el: '.swiper-pagination',
        type: 'bullets',
      },
  });

app/views/items/_pickup-container.html.haml
.pickup-container
  %h2.pickup-head ピックアップカテゴリー
  .items-box-container.clerfix
    %h3.text-center
      =link_to 'レディース 新着アイテム', '', class: 'link-blue'
    .items-box-content
      - @ladies.each do |item|
        .items-box
          = link_to item_path(item.id) do
            .items-box-photo
              = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
            .items-box-body
              %h3.items-box-name
                = item.name
              .items-box-num
                .items-box-price
                  = item.price
                .font-2
                  %i.icon-like-border
                  %span
              %p.item-box-tax (税込)
    .view-all
      %a{:href => "/jp/category/1/"} すべての商品を見る

  .items-box-container.clerfix
    %h3.text-center.text-mercari-blue
      =link_to 'メンズ 新着アイテム', '', class: 'link-blue'
    .items-box-content
      - @mens.each do |item|
        .items-box
          = link_to item_path(item.id) do
            .items-box-photo
              = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
            .items-box-body
              %h3.items-box-name
                = item.name
              .items-box-num
                .items-box-price
                  = item.price
                .font-2
                  %i.icon-like-border
                  %span
              %p.item-box-tax (税込)
    .view-all
      %a{:href => "/jp/category/1/"} すべての商品を見る

  .items-box-container.clerfix
    %h3.text-center
      =link_to 'ベビー・キッズ 新着アイテム', '', class: 'link-blue'
    .items-box-content
      - @kids.each do |item|
        .items-box
          = link_to item_path(item.id) do
            .items-box-photo
              = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
            .items-box-body
              %h3.items-box-name
                =item.name
              .items-box-num
                .items-box-price
                  = item.price
                .font-2
                  %i.icon-like-border
                  %span
              %p.item-box-tax (税込)
    .view-all
      %a{:href => "/jp/category/1/"} すべての商品を見る

  .items-box-container.clerfix
    %h3.text-center
      =link_to 'コスメ・香水・美容 新着アイテム', '', class: 'link-blue'
    .items-box-content
      - @cosmes.each do |item|
        .items-box
          = link_to item_path(item.id) do
            .items-box-photo
              = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
            .items-box-body
              %h3.items-box-name
                = item.name
              .items-box-num
                .items-box-price
                  = item.price
                .font-2
                  %i.icon-like-border
                  %span
              %p.item-box-tax (税込)
    .view-all
      %a{:href => "/jp/category/1/"} すべての商品を見る

.pickup-container
  %h2.pickup-head ピックアップブランド
  %h3.text-center
    =link_to 'シャネル 新着アイテム', '', class: 'link-blue'
  .items-box-content
    - @chanels.each do |item|
      .items-box
        = link_to item_path(item.id) do
          .items-box-photo
            = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
          .items-box-body
            %h3.items-box-name
              = item.name
            .items-box-num
              .items-box-price
                = item.price
              .font-2
                %i.icon-like-border
                %span
            %p.item-box-tax (税込)
  .view-all
    %a{:href => "/jp/category/1/"} すべての商品を見る

  .items-box-container
    %h3.text-center
      =link_to 'ルイ ヴィトン 新着アイテム', '', class: 'link-blue'
    .items-box-content
      - @vuitton.each do |item|
        .items-box
          = link_to item_path(item.id) do
            .items-box-photo
              = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
            .items-box-body
              %h3.items-box-name
                = item.name
              .items-box-num
                .items-box-price
                  = item.price
                .font-2
                  %i.icon-like-border
                  %span
              %p.item-box-tax (税込)
  .view-all
    %a{:href => "/jp/category/1/"} すべての商品を見る

  .items-box-container
    %h3.text-center
      =link_to 'シュプリーム 新着アイテム', '', class: 'link-blue'
    .items-box-content
      - @items.each do |item|
        .items-box
          = link_to item_path(item.id) do
            .items-box-photo
              -# = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
            .items-box-body
              %h3.items-box-name
                = item.name
              .items-box-num
                .items-box-price
                  = item.price
                .font-2
                  %i.icon-like-border
                  %span
              %p.item-box-tax (税込)
    .view-all
      %a{:href => "/jp/category/1/"} すべての商品を見る

  .items-box-container
    %h3.text-center
      =link_to 'ナイキ 新着アイテム', '', class: 'link-blue'
    .items-box-content
      -@items.each do |item|
        .items-box
          = link_to item_path(item.id) do
            .items-box-photo
              -# = image_tag item.images.first(), size:'300x300', class: 'lazyloaded'
            .items-box-body
              %h3.items-box-name
                = item.name
              .items-box-num
                .items-box-price
                  = item.price
                .font-2
                  %i.icon-like-border
                  %span
              %p.item-box-tax (税込)
    .view-all
      %a{:href => "/jp/category/1/"} すべての商品を見る

app/views/items/index.html.haml
.main-content
  .header
    = render 'header'
  .main-visual
    = render 'main-visual'
  .main
    = render 'pickup-container'
  .footer
    = render 'footer'

app/views/items/purchase.html.haml
.single-container
  %header.single-header
    %h1
      %a{:href => "/"}
        %img{:alt => "mercari", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?1073571291"}/

%main.single-main
  %section.single-main_content
    %h2.single-head 購入を確定しますか？
    %section.buy-content
      .buy-content-inner
        .buy-item-image
          = image_tag 'neko1.jpg'
        %p.buy-item-name moussy クラッシュデニム25
        %form.buy-form
          %p.buy-price
            ¥ 3,500
            %span.item-shipping-fee 送料込み
          %p.point
            ポイントはありません
          %ul.buy-price-table
            %li.buy-price-row
              .buy-price-left 支払い金額
              .buy-price-rigth
                %span ¥ 3,500
          %button.buy-btn{:disabled => "disabled", :type => "submit"} 購入する
          %input#user_info_is_not_complete{:type => "hidden"}/
    %section.buy-user-info
      .buy-user-inner
        %h3 配送先
        %address.buy-user-info-text
          〒612-8136
          %br/
          京都府 京都市伏見区
          向島四ツ谷池
          市営住宅14ー1 5ー8ー208
          %br/
          遠藤 康平
        %p.buy-user-info-edit
          %span 変更する
          = fa_icon 'chevron-right',class:"icon-arrow"
    %section.buy-content-payment
      .buy-content-inner
        %h3 支払い方法
        %p.buy-user-info-text
          %br/
          \/
        %a.buy-user-info-fix
          %span 変更する
          = fa_icon 'chevron-right',class:"icon-arrow"







  %footer.single-footer
    %nav
      %ul.footer-text
        %li
          %a{:href => "https://www.mercari.com/jp/privacy/"} プライバシーポリシー
        %li
          %a{:href => "https://www.mercari.com/jp/tos/"} メルカリ利用規約
        %li
          %a{:href => "https://www.mercari.com/jp/tokutei/"} 特定商取引に関する表記
    %a.single-footer-logo
      %img{:alt => "mercari", :height => "65", :src => "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?1073571291", :width => "80"}/
    %p
      %small © 2019 Mercari

app/views/items/show.html.haml
-userName = @item.user.family_name + @item.user.first_name
-prevItemId = @item.id - 1
-nextItemId = @item.id + 1
#items_show
  .main-content
    .header
      = render 'header'
    .main
      .item
        .item-title
          = @item.name
        .item-main
          .image-box
            .image-box__pickup
              = image_tag @item.images.first(), size:'300x300'
              .image-box__pickup__sold

            .image-box__bottom
              -@item.images.each do |image|
                .image-box__bottom__image
                  = image_tag image, size:'75x78'

          .item-main__list
            .item-main__list__row.item-main__list__exhibitor
              .item-main__list__row--name
                出品者
              .item-main__list__row--content
                =link_to '', class:'link-mercari-blue' do
                  = @item.user.nickname
                .content__eva
                  .content__eva--para
                    =fa_icon 'smile-o', class:'good'
                    ="#{896}"
                  .content__eva--para.content__eva--soso
                    =fa_icon 'meh-o', class:'soso'
                    ="#{27}"
                  .content__eva--para.content__eva--bad
                    =fa_icon 'frown-o', class:'bad'
                    ="#{4}"
            .item-main__list__row.item-main__list__category
              .item-main__list__row--name
                カテゴリー
              .item-main__list__row--content
                =link_to "#{@item.category.name}", '', class:'link-mercari-blue'
                -# =link_to '', class:'link-mercari-blue' do
                -#   =fa_icon 'chevron-right',class:"icon-arrow"
                -#   ="#{'バッグ'}"
                -# =link_to '', class:'link-mercari-blue' do
                -#   =fa_icon 'chevron-right',class:"icon-arrow"
                -#   ="#{'ショルダーバッグ'}"
            .item-main__list__row.item-main__list__brand
              .item-main__list__row--name
                ブランド
              .item-main__list__row--content
                -if(false)
                  =link_to "#{'コーチ'}", '', class:'link-mercari-blue'
            .item-main__list__row.item-main__list__status
              .item-main__list__row--name
                商品の状態
              .item-main__list__row--content
                = @item.status
            .item-main__list__row.item-main__list__ship-burden
              .item-main__list__row--name
                配送料の負担
              .item-main__list__row--content
                =@item.shipping_agency
            .item-main__list__row.item-main__list__ship-method
              .item-main__list__row--name
                配送の方法
              .item-main__list__row--content
                メルカリ便
            .item-main__list__row.item-main__list__disp-area
              .item-main__list__row--name
                配送元地域
              .item-main__list__row--content
                =link_to "#{@item.state}", '', class:'link-mercari-blue'
            .item-main__list__row.item-main__list__ship-date
              .item-main__list__row--name
                発送日の目安
              .item-main__list__row--content
                =@item.duration

        .item-price
          %span.item-price--price
            ="\¥#{@item.price}"
          %span.item-price--tax
            (税込)
          %span.item-price--postage

            ="#{'送料込み'}"
        -# - if (@item.user_id = current_user)
        -#   .buy_btn
        -#     =link_to "編集へ", root_path, class:'buy_btn'
        - if (@item.sold_out == false)
          .buy_btn
            = link_to item_purchases_path(@item), class:'buy_btn' do
              購入画面に進む
        - else
          .buy_btn.sold_out
            売り切れました

        %p.item-description.clerfix
          
          -text = "■商品ご覧頂き、誠にありがとうございます。\n※今だけ、フォロワーになって下さった方に、300円のお値引きサービス中！！\n\n私の商品検索は、\n#Boon・バッグ\n検索してください。\n\n質問がありましたらコメントでよろしくお願いします！\n■ 商品説明 ■\nまずはプロフを確認してください☆\n\n■ 商品詳細 ■\nシンプルな落ち着いたお色味でどんな場面にも合い、\nどんな服にも合わせやすいお鞄です。使用感有！角擦れはございませんが\n使わなくなったのでどなたか使っていただける方お願いします。\n製造番号　H2K-9294\n\n【ブランド】\nCOACH　コーチ\n\n【商品名】\nコーチ大き目シンプル\n\n【仕様】\n外ポケット１　内ポケット４\n\n【サイズ】\n縦：32\n横：31\n幅：7\n紐：130 多少調節可能\n\n＊他にも数多くの商品を出品しているので、ぜひご覧ください。\n＊複数購入、お取り置き(５日まで)もできるので、お気軽にお声がけくださいませ。\n＊中古品になりますので、予めご理解いただきますよう、お願い致します^_^\n※自宅保管、素人検品、素人寸法の誤差などにご理解がない方、神経質な方、完璧な物が欲しい方は購入お控えください。\n\n#シンプル #かわいい #大き目 #かばん #バッグ"
          = @item.description
          = simple_format(text, {})

       

    .chat
      .message-box
        .message-box__icon
          = image_tag 'mercari_icon.png', size:'40x40'
        .message-box__content
          .message-box__content__message
            出品者がコメントを削除しました
          .message-box__content__info
            200日前
    .prev-next-items
      -if(prevItemId != 0 && (prevItem = Item.find_by(id: prevItemId)) != nil)
        =link_to item_path(prevItemId), class:"nav-link link-mercari-blue" do
          =fa_icon 'chevron-left',class:"icon-arrow"
          =prevItem.name
      -if((nextItem = Item.find_by(id: nextItemId)) != nil)
        =link_to item_path(nextItemId), class:"nav-link link-mercari-blue" do
          =nextItem.name
          =fa_icon 'chevron-right',class:"icon-arrow"
    .sns
      .sns__item.sns__facebook
        =link_to '' do
          =fa_icon 'facebook-square 3x'
      .sns__item.sns__twitter
        =link_to '' do
          =fa_icon 'twitter-square 3x', class:'link-mercari-blue'
      .sns__item.sns__pinterest
        =link_to '' do
          = image_tag 'pinterest.png', size:'38x38'
    -if(@userItems.length > 1)
      .pickup-container
        .items-box-container
          %h3.text-center
            =link_to "#{userName}さんのその他の出品", '', class: 'link-blue'
          -for i in 0..((@userItems.length - 1) / 3)
            .items-box-content
              -for j in 0..2
                -if(@userItems[j] != nil)
                  .items-box
                    %a{:href => "/"}
                      .items-box-photo
                        = image_tag 'neko1.jpg', alt: '', height: '100%', width: '100%', class: 'lazyloaded'
                      .items-box-body
                        %h3.items-box-name
                          =@userItems[j].name
                        .items-box-num
                          .items-box-price
                            ="\¥#{@userItems[j].price}"
                        %p.item-box-tax (税込)

    -if(@cateItems.length > 1)
      .items-box-container
        %h3.text-center
          =link_to "#{@item.category.name}その他の出品", '', class: 'link-blue'
        .items-box-content
          -for i in 0..(@cateItems.length - 1)
            -if(@cateItems[i] != nil)
              .items-box
                %a{:href => "/"}
                  .items-box-photo
                    = image_tag 'neko1.jpg', alt: '', height: '100%', width: '100%', class: 'lazyloaded'
                  .items-box-body
                    %h3.items-box-name
                      =@cateItems[i].name
                    .items-box-num
                      .items-box-price
                        ="\¥#{@cateItems[i].price}"
                    %p.item-box-tax (税込)


    .footer
      = render 'footer'


-# = @item.category.parent.parent.name
-# = @item.category.parent.name
-# = @item.category.name
-# = @item.brand.name

app/views/items/test.html.haml
-# %ul.main__catagory
-#   - @categories.each do |category1|
-#     %li.main__catagory--list.matchHeight
-#       = category1.name
-#       %ul.sub__catagory.matchHeight
-#         - category1.children.each do |category2|
-#           %li.sub__catagory--list
-#             = category2.name
-#             %ul.sub__sub__catagory
-#               - category2.children.each do |category3|
-#                 %li
-#                   = category3.name