config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'purchase/index'
  get 'purchase/done'
  get 'card/new'
  get 'card/show'
  root to: 'items#index'
  get 'items/test' => 'items#test'
  resources :users do
    get 'sign_up_menu', on: :collection
    get 'phone_registration', on: :collection
    get 'complete_registration', on: :collection
    get 'information', on: :collection
    get 'logout', on: :collection
    get 'payment', on: :collection
    put 'information_update', on: :member
    put 'phone_confirmation', on: :member
    put 'phone_authenticated', on: :member
    get 'profile', on: :collection
    resources :addresses
    resources :payments
  end
  resources :items do
    resources :purchases, only: :index do
      post 'pay', on: :collection
      get 'done', on: :collection
    end
  end
  namespace :api do
    resources :items, only: :new, defaults: { format: 'json' }
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"

  before_action :set_category
  
  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = "sk_test_ea08d8eb3daefb829e554156"
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to payment_users_path
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = "sk_test_ea08d8eb3daefb829e554156"
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = "sk_test_ea08d8eb3daefb829e554156"
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  private
  def set_category
    @categories = Category.eager_load(children: :children).where(ancestry: nil)
  end
end

app/views/card/new.html.haml
#users_payment
  .main-content
    .header.mypape_header
      = render 'items/header',layout: 'application'
    %nav.bread-crumbs
      %ul
        %li
          %a
            %span メルカリ
          =fa_icon 'chevron-right',class:"icon-arrow"
        %li.nowpage
          %span マイページ

    %main.mypage-container
      //left menu
      = render partial: 'users/mypage-left'

      .right-content
        .heading
          支払い方法
        .main
          .payments
            クレジットカード一覧
            .payment
              .payment__credit_card
            = form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %label カード番号
              = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
              .payment__credit_card--icon
                = image_tag "mc_vrt_pos.svg", width:"32px"
              %br
              %label 有効期限
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月/
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年
              %br
              %label セキュリティコード
              = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
              #card_token
              = submit_tag "追加する", id: "token_submit"
        .bottom
          =link_to '',class:"nav-link link-mercari-blue" do
            ='支払い方法について'
            =fa_icon 'chevron-right',class:"icon-arrow"

    .footer
      = render "items/footer",layout: 'application'

app/views/card/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する